// <auto-generated />
using BancodeDados_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDeDados_BackEnd.Migrations.FrequenciaDbMigrations
{
    [DbContext(typeof(FrequenciaDb))]
    partial class FrequenciaDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BancodeDados_Backend.Models.Frequencia", b =>
                {
                    b.Property<int>("Id_frequencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_frequencia"));

                    b.Property<int>("Faltas")
                        .HasColumnType("int");

                    b.Property<int>("Id_matriculaFK")
                        .HasColumnType("int");

                    b.Property<int>("Presenca")
                        .HasColumnType("int");

                    b.HasKey("Id_frequencia");

                    b.ToTable("Frequencias");
                });
#pragma warning restore 612, 618
        }
    }
}
