// <auto-generated />
using BancodeDados_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDeDados_BackEnd.Migrations.AvaliacaoDbMigrations
{
    [DbContext(typeof(AvaliacaoDb))]
    [Migration("20251112125332_Avaliacao")]
    partial class Avaliacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BancodeDados_Backend.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_avaliacao"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_turmaFK")
                        .HasColumnType("int");

                    b.Property<float>("Nota")
                        .HasColumnType("float");

                    b.HasKey("Id_avaliacao");

                    b.ToTable("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
