// <auto-generated />
using BancodeDados_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDeDados_BackEnd.Migrations.MatriculaDbMigrations
{
    [DbContext(typeof(MatriculaDb))]
    [Migration("20251112125530_Matricula")]
    partial class Matricula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BancodeDados_Backend.Models.Matricula", b =>
                {
                    b.Property<int>("Id_matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_matricula"));

                    b.Property<string>("Data_matricula")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_alunoFK")
                        .HasColumnType("int");

                    b.Property<int>("Id_turmaFK")
                        .HasColumnType("int");

                    b.HasKey("Id_matricula");

                    b.ToTable("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
