// <auto-generated />
using BancodeDados_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDeDados_BackEnd.Migrations.NotaDbMigrations
{
    [DbContext(typeof(NotaDb))]
    [Migration("20251112125545_Nota")]
    partial class Nota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BancodeDados_Backend.Models.Nota", b =>
                {
                    b.Property<int>("Id_nota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_nota"));

                    b.Property<int>("Id_avaliacaoFK")
                        .HasColumnType("int");

                    b.Property<int>("Id_matriculaFK")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id_nota");

                    b.ToTable("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
