// <auto-generated />
using BancodeDados_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDeDados_BackEnd.Migrations.DisciplinaDbMigrations
{
    [DbContext(typeof(DisciplinaDb))]
    [Migration("20251112125450_Disciplina")]
    partial class Disciplina
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BancodeDados_Backend.Models.Disciplina", b =>
                {
                    b.Property<int>("Id_disciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_disciplina"));

                    b.Property<int>("Carga_horaria")
                        .HasColumnType("int");

                    b.Property<int>("Id_cursoFK")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_disciplina");

                    b.ToTable("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
